# Generated by Django 5.2.1 on 2025-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_validacion_citas_unicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='email',
        ),
        migrations.AlterField(
            model_name='responsable',
            name='email',
            field=models.EmailField(db_index=True, default='sin_email@temp.com', help_text='Email del responsable (para contacto)', max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='responsable',
            constraint=models.UniqueConstraint(fields=('tipodocumento', 'documento'), name='unique_responsable_documento', violation_error_message='Ya existe un responsable con este documento.'),
        ),
        migrations.AddConstraint(
            model_name='trabajador',
            constraint=models.UniqueConstraint(fields=('tipodocumento', 'documento'), name='unique_trabajador_documento', violation_error_message='Ya existe un trabajador con este documento.'),
        ),
    ]
